### ISSUE TITLE
Опечатка в файле примера linked_list.rs

### ISSUE THREAD

**Issue by andreevlex** [ruRust/rust-by-example-ru#33]
В файле примера https://github.com/ruRust/rust-by-example-ru/blob/master/examples/custom_types/enum/testcase_linked_list/linked_list.rs
есть комментарий вида `// Мы не можем завладеть 'tale', т.к. 'self' заимствован;`
Переменная называется tail, а в комментарии tale

**Comment by vessd** [comment]
https://github.com/ruRust/rust-by-example-ru/blob/master/CONTRIBUTING.md#Я-нашёл-опечатку-в-примере-x
