### ISSUE TITLE
Перевод: Раздел "7.5.2 Ограничитель шаблонов" некорректный перевод.

### ISSUE THREAD

**Issue by vl0ft** [ruRust/rust-by-example-ru#43]
[Оригинал](https://rustbyexample.com/flow_control/match/guard.html):

> (x, _) if x % 2 == 1 => println!("The first one is **odd**"),

[Перевод](https://github.io/rust-by-example-ru/flow_control/match/guard.html):

> (x, _) if x % 2 == 1 => println!("Первое число **чётно**"),

Нечётно.

**Comment by Gordon-F** [comment]
@vl0ft Буду рад PR :)

**Comment by vl0ft** [comment]
Надеюсь, ничего не порушил.
-*волнуется*-

**Comment by petrochenkov** [comment]
@vl0ft 
Ничего не порушил, но PR не в тот репозиторий :)

**Comment by vl0ft** [comment]
>_<

**Comment by petrochenkov** [comment]
@vl0ft 
закрыть PR там, открыть тут

**Comment by vl0ft** [comment]
Сейчас всё верно?

**Comment by petrochenkov** [comment]
@vl0ft 
да, теперь правильно
