### ISSUE TITLE
Преобразовать в mdbook

### ISSUE THREAD

**Issue by BORN2LOSE** [ruRust/rust-by-example-ru#61]
Случайно обнаружил этот **PR**, когда в основном репозитории не нашел бекенда и фронтенда.
Уже как неделю начали конвертировать книгу: https://github.com/rust-lang/rust-by-example/pull/897
Как-то могу помочь ? Точнее готов помочь с этим всем.
P.S. Темной темы очень не хватает 😊

**Comment by andreevlex** [comment]
Готово
