### ISSUE TITLE
Актуализация перевода RBE

### ISSUE THREAD

**Issue by andreevlex** [ruRust/rust-by-example-ru#70]

**Comment by andreevlex** [comment]
Реализация задуманного https://github.com/ruRust/community/issues/1

**Comment by andreevlex** [comment]
В текущей версии есть проверка правописания, кто может подсказать какие файлы отвечают за это?

**Comment by Gordon-F** [comment]
@andreevlex проверка происходит с использованием Яндекс.Спеллер.

.yaspellerrc - словарь исключений.

Сама проверка в makefile (последняя строка)
```make
test: node_modules/yaspeller
	@$(foreach src,$(srcs),$(RUSTC_NT) $(src) || exit;)
	./check-line-length.sh
	./check-line-length-md.sh
	./check-links.sh
	$(YASPELLER) --only-errors README.md CONTRIBUTING.md examples
```

**Comment by andreevlex** [comment]
#110  - крайная хотя бы частично переведенная глава.
@Gordon-F @BORN2LOSE

**Comment by andreevlex** [comment]
На данный момент в `mdbook` пренесены все переведенные главы.
Надо наладить `spelling check and deployment`, чтобы сказать что актуализация RBE завершена.

**Comment by andreevlex** [comment]
Закрываем?

**Comment by andreevlex** [comment]
Я перетащил книгу на mdBook и попутно перевел несколько глав.
Надо дальше переводить книгу, продолжим перевод в рамках данной задачи?

**Comment by BORN2LOSE** [comment]
Отлично @andreevlex  😎 
Насчёт дальнейшего перевода я не уверен, т.к. лично у меня сейчас не хватает времени.
