### ISSUE TITLE
Исправить битые ссылки

### ISSUE THREAD

**Issue by Gordon-F** [ruRust/rust-by-example-ru#8]
Необходимо исправить битые ссылки. Для примера страница https://rurust.github.io/rust-by-example-ru/hello/print.html. Внизу ссылки macros, struct и traits не работают.

**Comment by izhscorp** [comment]
Исправить битую ссылку `print display` `(https://rurust.github.io/hello/print/print_display.html)` на странице [Кортежи](https://rurust.github.io/rust-by-example-ru/primitives/tuples.html).

**Comment by Gexon** [comment]
https://rurust.github.io/rust-by-example-ru/flow_control/match/custom_types/enum.html - 404
ссылка отсюда https://rurust.github.io/rust-by-example-ru/flow_control/match/destructuring/destructure_enum.html
